# Generated by Django 4.2.7 on 2024-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_post_published_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to='post_covers/'),
        ),
    ]
