# Generated by Django 4.2.7 on 2024-05-15 22:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_post_cover_alter_post_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
