# Generated by Django 4.2.7 on 2024-05-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='post_covers/default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='post_covers/default.png', null=True, upload_to='post_covers/'),
        ),
    ]
