# Generated by Django 4.2.7 on 2024-05-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='post_covers/default.png', null=True, upload_to='post_covers/'),
        ),
    ]
