# Generated by Django 4.2.7 on 2024-05-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='post_covers/default.png', null=True, upload_to='user_profile/'),
        ),
    ]
