# Generated by Django 4.2.7 on 2024-05-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='user_profile/user.jpg', null=True, upload_to='user_profile/'),
        ),
    ]
